name = "shiryoku-backend"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "shiryoku-db"
database_id = "5419a4fe-46f6-495a-8d35-0df22e7f27eb"
